name: flutter_staggered_grid
description: Provides staggered, masonry, quilted, woven, and staired grid layouts for Flutter.
version: 0.0.2
homepage: https://github.com/MuhammadFahad0/flutter_staggered_grid
repository: https://github.com/MuhammadFahad0/flutter_staggered_grid
issue_tracker: https://github.com/MuhammadFahad0/flutter_staggered_grid/issues
topics:
  - flutter
  - grid
  - masonry

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
